### ISSUE TITLE
Inconsistent Damage (M1911)

### ISSUE THREAD

**Issue by ghost** [VeniceUnleashed/VeniceUnleashed#177] opened 2015-12-28 18:13 UTC
The Video speaks for itself. Since it isn't damage collecting because we were on Ts and they really shot/hitted only one bullet. https://youtu.be/bpk5498t3JQ

**Comment by OrfeasZ** [comment] 2017-03-19 00:22
Further research suggests that this is caused by a hit registering more than once while the bullet is travelling through a player's body, due to the increased update rate.

**Comment by kiwidoggie** [comment] 2017-03-20 13:55
See: http://www.youtube.com/watch?v=3vDOC1V6GM8
Looks similar.

**Comment by OrfeasZ** [comment] 2018-05-09 09:46
Fixed in build 12914.

**Closed as completed by OrfeasZ** 2018-05-09 09:46 UTC
Labels: bug, high priority
