### ISSUE TITLE
[Bug] Spectator Mode invisible players 

### ISSUE THREAD

**Issue by VladMcCaffrey** [VeniceUnleashed/VeniceUnleashed#206] opened 2016-01-04 00:23 UTC
When switching between players. Sometimes players are totally invisible. but then appear after sometime.

Video: https://www.youtube.com/watch?v=ZgCrsENlmfs

**Comment by kiwidoggie** [comment] 2016-01-14 13:47
Duplicate of  https://github.com/EmulatorNexus/VeniceUnleashed/issues/133

**Closed as completed by kiwidoggie** 2016-01-14 13:47 UTC
Labels: duplicate

**Comment by rierei** [comment] 2016-01-16 17:30
This bug has been solved in a build that has not been available?

This issue occurs after observing a player within a jet or helicopter making the first person draw to be invisible at others.

In the case of #133 i believe it has already been solved some time ago.

**Comment by rierei** [comment] 2016-01-16 22:38
Video: [VU_invisibleplayer](https://vid.me/3NK7)

**Comment by kiwidoggie** [comment] 2016-01-17 01:08
The issue was never resolved, we were made aware of it, but haven't had time to look into it yet. We will be looking in to it as soon as we can.
