### ISSUE TITLE
Game Disconnect every 5-10 mins

### ISSUE THREAD

**Issue by IbrahimSystem** [VeniceUnleashed/VeniceUnleashed#167] opened 2015-12-26 12:26 UTC
i play normaly but after 5 mins or 10 mins the game disconnects it say's that the connection to zeus backend has been lost after i click reconnect the client close it self and i will be forced to rerun it.

**Comment by OrfeasZ** [comment] 2016-01-03 12:41
Disconnections can be caused by a bad internet connection or routing to our backend services, so there's nothing we can currently do about that until we expand our global server availability.
As for the crash, it was fixed in build 10827.

**Closed as completed by OrfeasZ** 2016-01-03 12:41 UTC
