### ISSUE TITLE
WebUI menu not rendering at >=4K resolutions

### ISSUE THREAD

**Issue by Keksmonster31** [VeniceUnleashed/VeniceUnleashed#100] opened 2015-05-10 00:02 UTC
I played the game today and set my resolution to 2560x1440 and downscaled it with Nvidia DSR.
Logging in and selecting my soldier still works but the rest of the menus are invisible. I tried screenshotting it but the menu is visible on screenshots.

**Comment by 3ti65** [comment] 2015-05-10 02:27
I can confirm this bug. Same resolution in my case.

It's very likely that it's caused by DSR since enabling / disabling SLI does not affect the behaviour of the bug in any way. (In my case as tested)

Quick workaround to keep testing in 2560x1440:

Go to windowed mode by hitting Alt + Enter. Downscale window size until the menu magically reappears at a certain point.

**Comment by ExtReMLapin** [comment] 2015-05-11 16:46
Same at 5760x1080

But maybe Y/X pos problem.

**Comment by OrfeasZ** [comment] 2015-09-25 18:26
This has been fixed in build 9843 (not live yet).

**Closed as completed by OrfeasZ** 2015-09-25 18:26 UTC
Labels: bug
