### ISSUE TITLE
Prompt a message when VU isn't activated

### ISSUE THREAD

**Issue by 3ti65** [VeniceUnleashed/VeniceUnleashed#386] opened 2019-01-07 18:39 UTC
Currently it just closes again with an empty log file, there should be a message prompted that the game isn't activated.

**Comment by 3ti65** [comment] 2019-01-09 09:59
The EA Auth window apparently popped up on the VPS, i didnt see that.

Would be nice to get some sort of console output in that case though.

Something like "Failed to activate Battlefield 3, please activate your game doing this and that"

**Comment by OrfeasZ** [comment] 2019-01-14 17:46
Looks like the cause of the EA activation window not showing up was VU being installed in a different directory than BF3. This has been fixed in build `14377` and the activation dialog should properly present itself.

**Closed as completed by OrfeasZ** 2019-01-14 17:46 UTC
Labels: bug, help wanted
