### ISSUE TITLE
Thermal overlay from MAV not removed when switching player

### ISSUE THREAD

**Issue by Xulunix** [VeniceUnleashed/VeniceUnleashed#124] opened 2015-05-11 17:51 UTC
Spectating an player using the MAV and switching to an other player doesn't remove the thermal overlay for other players. Switching to other players causes the view to appear with the termal overlay.
http://yolarrydabomb.net/img/2015/05/11133547-26Mj6-1.png

Spectating the MAV until the player exits it removes the thermal overlay

**Comment by OrfeasZ** [comment] 2015-05-11 18:03
Duplicate of #116

**Closed as completed by OrfeasZ** 2015-05-11 18:03 UTC
