### ISSUE TITLE
Crash when accessing OccluderVolumeEntity.transform

### ISSUE THREAD

**Issue by Powback** [VeniceUnleashed/VeniceUnleashed#450] opened 2019-07-22 09:05 UTC
```

function GameObjectManager:OnEntityCreateFromBlueprint(p_Hook, p_Blueprint, p_Transform, p_Variation, p_Parent)
    local s_SpawnedEntities = p_Hook:Call()

    for l_Index, l_Entity in ipairs(s_SpawnedEntities) do
            if(l_Entity:Is("SpatialEntity") and l_Entity.typeInfo.name ~= "OccluderVolumeEntity") then
                local s_Entity = SpatialEntity(l_Entity)
               print(s_Entity.transform)
            end
     end
end
```

Removing the OccluderVolumeEntity check causes a client crash on MP_Subway and most likely other maps.

**Comment by 3ti65** [comment] 2019-07-22 09:22
-> Something must be weird about the OccluderVolumeEntity.transform

**Comment by Powback** [comment] 2019-07-22 10:06
Probably also affects DynamicModelEntites, which turn into EntityBusPeers when the object is destroyed or unloaded. Unconfirmed, might be irrelevant.

**Comment by OrfeasZ** [comment] 2020-02-06 17:47
Can't reproduce this in the latest build. Closing.

**Closed as completed by OrfeasZ** 2020-02-06 17:47 UTC
Labels: invalid, VeniceEXT
