### ISSUE TITLE
VU crashes every now and then

### ISSUE THREAD

**Issue by kiiks2000** [VeniceUnleashed/VeniceUnleashed#893] opened 2023-01-16 00:43 UTC
Crash ID: a7041d8f-8463-4ba4-888d-adcf94a30df1
Build Number: 19969
Release Branch: dev

**Comment by FlashHit** [comment] 2023-03-12 13:49
Will probably get fixed with vext 2.0
Duplicate of https://github.com/VeniceUnleashed/VeniceUnleashed/issues/879

**Closed as not planned by FlashHit** 2023-03-12 13:49 UTC
Labels: duplicate
