### ISSUE TITLE
Sound volume low when spectating

### ISSUE THREAD

**Issue by spooker0** [VeniceUnleashed/VeniceUnleashed#19] opened 2014-11-09 09:09 UTC
When you enter a server as a spectator, sound volume is low (almost muted) until you switch perspective or hit the escape (to go to menu) and then go back in.

**Comment by OrfeasZ** [comment] 2014-11-09 10:11
This is a known issue that is caused by an invalid UI state not being popped by the client.

**Comment by OrfeasZ** [comment] 2015-04-24 09:27
This has been fixed in build 8210.

**Closed as completed by OrfeasZ** 2015-04-24 09:27 UTC
Labels: bug, low priority
