### ISSUE TITLE
Mouse loses focus when pressing ESC

### ISSUE THREAD

**Issue by bigworld12** [VeniceUnleashed/VeniceUnleashed#107] opened 2015-05-10 13:21 UTC
hi , this problem occurred to me while i was in-game then pressed ESC  and after like 1 min the mouse focus is gone (you can't see mouse cursor or move it)

**Comment by OrfeasZ** [comment] 2015-05-10 13:23
Duplicate of #87

**Closed as completed by OrfeasZ** 2015-05-10 13:23 UTC
