### ISSUE TITLE
Chat window stays after being kicked

### ISSUE THREAD

**Issue by xerxes-at** [VeniceUnleashed/VeniceUnleashed#202] opened 2016-01-02 18:57 UTC
Chat window stays if it was visible while being kicked.

![vu_2016_01_02_19_46_19_779](https://cloud.githubusercontent.com/assets/5236639/12075717/de55f7e8-b189-11e5-987b-9ae8694c54e1.jpg)

**Comment by kiwidoggie** [comment] 2016-02-02 12:45
This is caused by VEXT not unloading plugins after being dropped or kicked from the server. Not sure what the implementation for this is supposed to be, adding NF to take a look.

**Comment by OrfeasZ** [comment] 2017-03-19 00:18
This should be fixed in the upcoming update.

**Closed as completed by OrfeasZ** 2017-03-19 00:18 UTC
Labels: bug, unverified
