### ISSUE TITLE
[Crash] Client crash when reconnecting to RM after a client crash.

### ISSUE THREAD

**Issue by FoolHen** [VeniceUnleashed/VeniceUnleashed#538] opened 2020-10-31 12:27 UTC
Sometimes after relaunching the client and reconnecting to the server after a crash it crashes again. For example, after crashing because of #537 . It doesn't always happen.
Example:
```
Crash when attempting to reconnect to server post a 'give up' silent crash.
Crash ID: fe3c5c8e-11a6-4078-b898-ec4c23e90d57
Build Number: 17182
Release Branch: prod
```
This was reported during the latest playtest, on October 25th. There might be more reported in #error_dumps channel.

Local dumps, from latest dev 17264.
[dumps.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/5469073/dumps.zip)

**Comment by OrfeasZ** [comment] 2020-11-12 04:04
Duplicate of #537

**Closed as completed by OrfeasZ** 2020-11-12 04:04 UTC
Labels: duplicate

**Comment by FoolHen** [comment] 2020-11-12 20:55
You sure its the same?

Crash ID: ee10c128-cc32-4c1f-895a-7143a0ca2e6f
Build Number: 17301
Release Branch: dev

**Comment by OrfeasZ** [comment] 2020-11-12 21:01
Seems like it yeah.

**Comment by FoolHen** [comment] 2020-11-12 21:11
Okay. Weird, I crashed after restarting the RM server while testing the fb images issue. So i didn't spawn any bots.
