### ISSUE TITLE
[Crash] Cloning certain instance types causes a crash

### ISSUE THREAD

**Issue by 3ti65** [VeniceUnleashed/VeniceUnleashed#308] opened 2018-05-08 14:26 UTC
Cloning certain types leads to a crash:

- [ ] UIGraphAsset
- [ ] VehicleSpawnReferenceObjectData

Testmods will follow.

**Comment by OrfeasZ** [comment] 2018-05-12 14:35
Duplicate of #301

**Closed as completed** 2018-05-12 14:35 UTC
Labels: duplicate
