### ISSUE TITLE
[Bug] NetEvents parameters seem to have a rare deserialization issue

### ISSUE THREAD

**Issue by 3ti65** [VeniceUnleashed/VeniceUnleashed#368] opened 2018-10-25 13:31 UTC
Happens very randomly and not very often, but it does happen.

Example:

Server sends this to client:

https://cdn.discordapp.com/attachments/171476437193326594/504801510132023316/unknown.png

Upon receiving:

https://cdn.discordapp.com/attachments/171476437193326594/504801708409356309/unknown.png

For some reason, this one parameter of type 'number' is deserialized as 'userdata'. 

The location of something like this occuring and when / if it occurs seems to be random, the above was just a caught example. So far there's been around 4-5 occurances.

Will extend the NetEventsParams test to feature a lot of NetEvents being passed shortly after each other.

**Comment by 3ti65** [comment] 2018-11-08 21:15
This is definitely an issue, keeps happening on different occasions. 

Often it falsely receives a DataContainer instead of a number or sth.

**Comment by Powback** [comment] 2018-11-14 08:35
I did some testing and was unable to reproduce an issue with netevents. 

Test:
Store an ID
Send ID to server/client
server/client verifies that it's the expected ID
increment ID and repeat.

After 500000+ I still haven't encountered a deserialization issue.

Edit:
I should also note that I've attempted to do the same thing using UpdateManager:Update without an updatepass filter, and that worked without issue.

One curious case though, Why are the values ints on the server side, but floats on the client side?

**Comment by OrfeasZ** [comment] 2018-11-14 09:54
`One curious case though, Why are the values ints on the server side, but floats on the client side?`

This is expected behavior because prior to Lua 5.3 there was no internal distinction between ints and floats (all lua numbers were doubles), and the NetEvent serialization code hasn't been appropriately updated. With that being said, I might make a few changes to create a distinction between the two types when it comes to NetEvents, but I don't think it really matters.

**Comment by 3ti65** [comment] 2018-11-14 09:59
Yo @Powback run your unit test together (repeatingly) with RM and see if it still holds up.

**Comment by OrfeasZ** [comment] 2018-12-09 19:56
Seems like this is fixed. Closing.

**Closed as completed by OrfeasZ** 2018-12-09 19:56 UTC
Labels: bug, help wanted, VeniceEXT
