### ISSUE TITLE
[Bug]Spectator Mode

### ISSUE THREAD

**Issue by VladMcCaffrey** [VeniceUnleashed/VeniceUnleashed#200] opened 2016-01-02 15:21 UTC
When clicking you mouse left or right click. The game turns off, with a crash.

**Comment by kiwidoggie** [comment] 2016-01-02 15:53
Duplicate of https://github.com/EmulatorNexus/VeniceUnleashed/issues/199

**Closed as completed by kiwidoggie** 2016-01-02 15:53 UTC
Labels: duplicate
