### ISSUE TITLE
Fullscreen Issues

### ISSUE THREAD

**Issue by Powback** [VeniceUnleashed/VeniceUnleashed#282] opened 2018-02-04 17:43 UTC
- [x] Missing alt+enter to get toggle fullscreen
- [x] If the game is started fullscreen you can't click anything certain times
- [ ] If the game settings is fullscreen, the VU main menu is displayed in a window at first launch, then set to fullscreen after you join a game.

**Comment by OrfeasZ** [comment] 2018-02-21 21:22
Can you elaborate on the third issue? Not sure I understand what you mean.

**Comment by Powback** [comment] 2018-02-21 21:24
1. Set window-setting to fullscreen ingame
2. Close the game
3. Launch the game. It is now windowed.
4. Join a game. You're now fullscreen, and input does not work.

**Comment by Powback** [comment] 2018-07-25 14:23
The recent update solves the "input not working" issue, but the other issues still persist. 

I have updated the original issue with the current state.

**Comment by OrfeasZ** [comment] 2018-08-17 22:12
Alt+Enter now works properly in build 13375. I couldn't reproduce the "starting in windowed" thing, but it sounds like a Frostbite issue anyway so I'm closing this.

**Closed as completed by OrfeasZ** 2018-08-17 22:12 UTC
Labels: bug, high priority, WebUI
