### ISSUE TITLE
Add setter to SoldierEntityData.Health

### ISSUE THREAD

**Issue by 3ti65** [VeniceUnleashed/VeniceUnleashed#239] opened 2017-08-23 21:28 UTC
The property .health on the SoldierEntityData in VU is readonly. Would be nice to have a public setter, e.g. to create a bleed out effect.

**Comment by kiwidoggie** [comment] 2017-08-28 03:44
This has been implemented in `SoldierEntity.health` on server in build 12209.

**Comment by FoolHen** [comment] 2017-10-17 09:33
@kiwidoggie it works, but it doesn't update the client. Only when you heal/take damage your health is updated.

**Comment by 3ti65** [comment] 2017-10-17 14:24
Might wanna reopen this, since the client should be up to date at all times. UI, Sound, etc is all influenced by the client health.

**Comment by OrfeasZ** [comment] 2017-11-08 14:35
Should be fixed in build 12239.

**Comment by FoolHen** [comment] 2017-11-09 12:57
@OrfeasZ 
Now it crashes the server when you modify its value

**Comment by OrfeasZ** [comment] 2017-11-09 17:39
@Raikem does it always crash or does it crash under specific conditions? Can you provide a test mod that causes this crash?

**Comment by FoolHen** [comment] 2017-11-09 17:51
Seem to crash always
[healthmod.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/1458654/healthmod.zip)
type your new health in chat

**Comment by OrfeasZ** [comment] 2017-11-09 23:04
This has been fixed (fully and finally) in build 12248.

This build also includes another addition to the server soldier, allowing the direct application of damage. The usage is:
```lua
player.soldier:ApplyDamage(damageInfo)
```

Where `damageInfo` is a `ServerDamageInfo` object. The `ServerDamageInfo` class exposes the following properties:
- position (Vec3)
- direction (Vec3)
- origin (Vec3)
- damage (float)
- distributeDamageOverTime (float)
- empTime (float)
- stamina (float)
- collisionSpeed (float)
- boneIndex (integer)
- isDemolitionDamage (bool)
- includeChildren (bool)
- isExplosionDamage (bool)
- shouldForceDamage (bool)
- isBulletDamage (bool)
- isClientDamage (bool)

Example usage:
```lua
local damageInfo = ServerDamageInfo()
damageInfo.damage = 99.0
damageInfo.position = soldier.transform.trans
damageInfo.direction = Vec3(0, 1, 0)
damageInfo.shouldForceDamage = true

soldier:ApplyDamage(damageInfo)
```

It should be noted that if you apply negative damage the soldier will be healed.

**Comment by FoolHen** [comment] 2017-11-10 17:44
@OrfeasZ 
Changing soldier.health doesn't work (tho it doesn't crash anymore). 
Creating a ServerDamageInfo object, even if its empty, crashes the server most of the time. When it doesn't crash, soldier:ApplyDamage(damageInfo) works fine.
[healthmod.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/1462206/healthmod.zip)

**Comment by OrfeasZ** [comment] 2017-11-10 18:06
That's odd, I can't reproduce locally.

**Comment by OrfeasZ** [comment] 2017-11-10 18:07
@Raikem can you capture one of these crashes and send me a dump?

**Comment by FoolHen** [comment] 2017-12-04 12:36
@OrfeasZ Newest update created a crash dump, here it is
[90938746-4027-44ba-b220-f8b333fd575b.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/1527018/90938746-4027-44ba-b220-f8b333fd575b.zip)

Also you might want to reopen this issue.

**Comment by FoolHen** [comment] 2018-01-01 12:48
@kiwidoggie can you try to replicate it? Keep typing "test" in chat until it crashes, sometimes it happens the first try and sometimes the 4th or 5th time.

**Comment by 3ti65** [comment] 2018-01-17 10:22
Please reopen this issue as its still not fixed.

**Comment by OrfeasZ** [comment] 2018-01-26 14:13
Fixed in build 12396

**Closed as completed by OrfeasZ** 2018-01-26 14:13 UTC
Labels: enhancement, high priority, VeniceEXT
