### ISSUE TITLE
[Feature] Allow bots to aim or use lock-on weapons (like the stinger)

### ISSUE THREAD

**Issue by Firjens** [VeniceUnleashed/VeniceUnleashed#650] opened 2021-06-30 19:49 UTC
Hello,

This ticket is sourced from https://github.com/Joe91/fun-bots/issues/80

On the fun-bots issue I suggested allowing bots to use stingers and JAVELIN-like lock-on weapons. This is not possible however as the contributors and the maintainer of that repo stated because bots cannot aim.

It'd be extremely nice to have the ability for bots to aim or to allow bots to use lock-on weapons (by locking on to a target). Please see the linked ticket above for more content.

**Comment by FlashHit** [comment] 2021-06-30 20:21
I guess it's a duplicate of #622

**Closed as completed** 2021-07-11 17:36 UTC
Labels: bug, duplicate
