### ISSUE TITLE
I run vu.exe I always black screen and a constant inscription loading

### ISSUE THREAD

**Issue by kremos** [VeniceUnleashed/VeniceUnleashed#68] opened 2015-04-02 08:00 UTC
Hi,I made all the updates 9 \ 9 and now when I run vu.exe I always black screen and a constant inscription loading. Nothing happens. What did I do wrong? :oops:  :(
WebUI_debug.log
Created new handler 1 - 1

Serving: vu://main/

Requested full assets: /webui/main/index.html

Failed to verify signature of vuic container.2

File does not exist in container.

Failed to locate /webui/main/index.htmlin packages.

Showing main menu.

Doing intro sequence.

Uncaught ReferenceError: WebUI is not defined
at (line 0)

Uncaught ReferenceError: WebUI is not defined
at (line 0)

**Comment by OrfeasZ** [comment] 2015-04-02 08:20
Duplicate of #67

**Closed as completed by OrfeasZ** 2015-04-02 08:20 UTC
