### ISSUE TITLE
Auto-Connect after freq change

### ISSUE THREAD

**Issue by AlexEe77** [VeniceUnleashed/VeniceUnleashed#168] opened 2015-12-26 13:10 UTC
Automatically join to the desired server with the right frequency. Maybe also add a `-connect IP`  parameter

**Comment by MAGICCC** [comment] 2015-12-26 15:45
Duplicate of https://github.com/EmulatorNexus/VeniceUnleashed/issues/165 and https://github.com/EmulatorNexus/VeniceUnleashed/issues/138

**Closed as completed** 2015-12-26 16:12 UTC
