### ISSUE TITLE
[Bug] Changed value of sliders in Mod Settings are not saved

### ISSUE THREAD

**Issue by paulhobbel** [VeniceUnleashed/VeniceUnleashed#885] opened 2022-12-03 00:10 UTC
There seems to be a bug where the values of range sliders in the Mod Settings are not stored correctly.

**Comment by FlashHit** [comment] 2023-03-12 13:45
Duplicate of https://github.com/VeniceUnleashed/VeniceUnleashed/issues/897

**Closed as not planned by FlashHit** 2023-03-12 13:45 UTC
Labels: duplicate
