### ISSUE TITLE
Mouse becomes useless when chat is closed

### ISSUE THREAD

**Issue by PrufessorOak** [VeniceUnleashed/VeniceUnleashed#103] opened 2015-05-10 06:48 UTC
If you open the chat on any of the option menus or deploy screen and close it by pressing Enter, the mouse becomes useless. Press escape to fix the issue.

**Comment by OrfeasZ** [comment] 2015-05-10 12:14
Duplicate of #87.

**Closed as completed by OrfeasZ** 2015-05-10 12:14 UTC
Labels: duplicate
