### ISSUE TITLE
The vu server crashes immediately when a game ends

### ISSUE THREAD

**Issue by 1154077** [VeniceUnleashed/VeniceUnleashed#896] opened 2023-02-12 08:14 UTC
The vu server crashes immediately when a game ends
The following file is the crash log
[b9fe2b0e-d7dc-4415-b78d-349cb92b759e.dmp.txt](https://github.com/VeniceUnleashed/VeniceUnleashed/files/10715608/b9fe2b0e-d7dc-4415-b78d-349cb92b759e.dmp.txt)
The website doesn't support dmp files, so I added the txt suffix

**Comment by FlashHit** [comment] 2023-03-12 13:46
Duplicate of https://github.com/VeniceUnleashed/VeniceUnleashed/issues/889

**Closed as not planned by FlashHit** 2023-03-12 13:46 UTC
Labels: duplicate
