### ISSUE TITLE
after login - text disappears

### ISSUE THREAD

**Issue by delukz** [VeniceUnleashed/VeniceUnleashed#38] opened 2014-12-28 10:50 UTC
text just seems to disappear here after I log in.
It shows me the make new soldier, after that nothing.
I have managed to make a soldier by typing it in blindly, so after making a soldier I see a menu pop up to the top left for about 1 second before it disappears.

Machine: GF970, i7 3930, 8 GB, Win 8.1, 1x 1440p + 1x 1080p

**Comment by OrfeasZ** [comment] 2014-12-28 13:09
@delukz Does the login screen work properly, or does it also have response issues?
Can you provide a screenshot or video of your problem?

**Comment by delukz** [comment] 2014-12-28 13:12
Here you go: https://www.youtube.com/watch?v=LirbTTiviOA

**Comment by OrfeasZ** [comment] 2014-12-28 13:26
This is a very odd issue indeed.
What's even more odd is that the loading indicator is rendering over the UI.

I will look into a few things and let you know if I need any additional information @delukz.

**Comment by OrfeasZ** [comment] 2014-12-28 13:28
Scrap that last thought, it just looks like the backdrop image isn't being loaded.
Still odd though.

**Comment by OrfeasZ** [comment] 2014-12-28 16:32
@delukz I have pushed a new update (build 7089) which includes several changes to the WebUI.
The update should be live within the next 15 minutes.

Let me know if you're still experiencing this issue with the new build, and if so, please attach to this issue the WebUI_debug.log file which will be generated in your BF3 installation directory.

**Comment by ghost** [comment] 2014-12-28 16:35
@OrfeasZ This update might fix issue #11, however, I can't reproduce the issue as I am rebuilding my PC.

**Comment by OrfeasZ** [comment] 2014-12-28 16:37
@win32re It looks like issue #11 might be related to outdated AMD GPU drivers for old-gen GPU hardware. I'll post more info on that issue.

**Comment by delukz** [comment] 2014-12-28 16:54
@OrfeasZ Got the update but did not solve the issue.

log file:

The key "target-densitydpi" is not supported.
    at / (line 4)

Warning: No route matches path "". Make sure you have <Route path=""> somewhere in your routes
    at /app/bundle.js (line 6)

**Comment by delukz** [comment] 2014-12-28 17:48
Managed to get a menu somehow after it started in a window mode, disappeared again once I left a game though.

**Comment by OrfeasZ** [comment] 2014-12-28 18:05
Try the following:
Run the game in windowed mode and after logging into your soldier try resizing the window and see if the main menu appears.

**Comment by delukz** [comment] 2014-12-28 18:49
Resizing works.

**Comment by OrfeasZ** [comment] 2014-12-28 18:51
So after resizing it the menu appears?

**Comment by delukz** [comment] 2014-12-28 19:07
Yes.

**Comment by OrfeasZ** [comment] 2014-12-28 19:08
Okay, so this might be related to #11 after all.
Unfortunatelly I can't look into it right now because I'm lacking some of my resources, so you will have to settle to this workaround for the time being.

**Comment by OrfeasZ** [comment] 2015-06-07 22:49
Duplicate of #11.

**Closed as completed by OrfeasZ** 2015-06-07 22:49 UTC
Labels: bug, duplicate
