### ISSUE TITLE
120hz, losing mouse and >30 players

### ISSUE THREAD

**Issue by narkotix781** [VeniceUnleashed/VeniceUnleashed#101] opened 2015-05-10 00:12 UTC
when playing on the 120hz server yesterday anything over 30 players was unplayable, however when it was less even on my 300+ms ping it was quite playable.

also a soldier appeared red in a death screen and i lost my in game mouse (for menu naviation and deplloyment screen) until i restarted.

**Comment by OrfeasZ** [comment] 2015-05-10 12:17
The first issue is related to the servers CPU not being to handle simulation for that many players.
The second issue is a duplicate of #87.

**Closed as completed by OrfeasZ** 2015-05-10 12:17 UTC
Labels: duplicate
