### ISSUE TITLE
[Bug] Problem with weapon slot selection via number buttons

### ISSUE THREAD

**Issue by 3ti65** [VeniceUnleashed/VeniceUnleashed#260] opened 2017-12-30 15:56 UTC
By default you can select weapons with the buttons 1-x.

I assigned the following weapons to the slots:

`player:SelectWeapon(WeaponSlot.WeaponSlot_0, weapon, { weaponAtt0, weaponAtt1 })	
player:SelectWeapon(WeaponSlot.WeaponSlot_1, pistol, { })
player:SelectWeapon(WeaponSlot.WeaponSlot_2, knife, { })
player:SelectWeapon(WeaponSlot.WeaponSlot_3, grenade, { })`

Now here's the weird bahavior:

Pressing Button 3, i'd expect it to be representing WeaponSlot_2. However, what button 3 represents depends on what you had previously selected.

Button 1 -> Selects Rifle
Button 3 -> Selects Knife (As expected) 
Button 4 -> _nothing happens_

Button 2 -> Selects Pisol
Button 3 -> Selects Grenade ??
Button 4 -> _nothing happens_

So depending on the previous selection, the mapping of the key is different.
Also some slots are not directly selectable for some reason.

I hope it's a bug within vEXT and not default engine behavior because fuck that.

**Testmod:**

[spawn-soldier.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/1648927/spawn-soldier.zip)

**Comment by OrfeasZ** [comment] 2017-12-30 16:05
The weapon selection call in VEXT does not make any assumptions about how weapon slots are managed. It maps 1-to-1 to the internal engine implementation.

**Comment by 3ti65** [comment] 2017-12-30 16:08
can u check if its set correctly? or any educated guess on why this happens?

webm:
https://gfycat.com/AcidicAromaticArgali

**Comment by OrfeasZ** [comment] 2017-12-30 16:12
I'll take a look.

**Comment by 3ti65** [comment] 2017-12-30 16:28
Spawning a kit 'manually' will not result in the same behavior, instead it will work as one would expect it to work. 

Key - Slot mapping is 1:1 when spawned manually.

**Comment by 3ti65** [comment] 2018-01-11 18:14
Scrollwheel works as expected, only the buttons mapping is messed up.

**Comment by Powback** [comment] 2018-01-12 07:56
I can verify the issue.
Scrollwheel selects the weapons as intended.

If I remember correctly:

Input:
1,3 = 4
2,3 = 3
1,4 = 3
2,4 = 4

**Comment by 3ti65** [comment] 2018-01-12 16:18
sometimes its also:

1 = 1
2 = 2
3 = 5
4 = 5

I'll include a testmod on the weekend.

**Comment by 3ti65** [comment] 2018-01-20 15:34
Testmod attached in the original post

**Comment by 3ti65** [comment] 2018-01-21 15:40
[spawn-soldier.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/1649859/spawn-soldier.zip)

Testmod added

Steps to reproduce:

1. Be dead. Type 'spawn'
2. Spawns player with: M416, Glock17, FirstAidKit, Defib, Knife, Grenade (in this order!)
3. Use Mouse Scroll Wheel to select the next / previous weapon -> works just fine / as expected
4. Use Buttons 1-6 to select different items. Does not work as expected. you get a very weird behaviour, also depending on what you had previously selected:

Input:
1,3 = 3
2,3 = 4
1,4 = 3
2,4 = 4

Please fix as this fucks up the whole usability of the buttons for selecting weapons.

**Comment by OrfeasZ** [comment] 2018-01-21 20:03
After some further investigation it looks like indeed this is intended behavior.  They way keys are bound in Frostbite seems to be as follows:

- `1` is bound to `ConceptSelectInventoryItem1`
- `2` is bound to `ConceptSelectInventoryItem2`
- `3` is bound to `ConceptSwitchToStaticGadget`
- `4` is bound to `ConceptSelectInventoryItem5`
- etc...

You can look at `Input/VeniceSoldierInputConcepts` or `Input/VeniceDefaultInputConcepts` (or maybe some other InputConcepts file) to get a better understanding of how keys are bound and what concepts they correspond to. Also, if you look in `Input/SoldierWeaponSwitching` you will find the configuration which dictates how weapon switches are handled (ie. after switching from slot `X` to `Y` should the client fire once and switch back to the previous weapon like a knife, etc.).

**Comment by OrfeasZ** [comment] 2019-04-06 18:42
I'm re-opening this because apparently this is still something we can't figure out. I'll have to see if I can create a proper inventory management mod or built-in library.

**Comment by OrfeasZ** [comment] 2019-04-21 18:18
Even though I haven't fully figured this out yet, here's how you can achieve what you're trying to do:

```
local function PatchSWSD(data)
    if data.isReadOnly then
        print('Making SWSD writable.')
        data:MakeWritable()
    end
    
    -- Modify the switch map to point to the right slot with no automatic switching.
    for i = 1, 7 do
        local mapData = data.directSwitchMap[i]

        print('Patching map data at index ' .. tostring(i))
        print('Current action: ' .. tostring(mapData.action))
        print('Current weapon: ' .. tostring(mapData.toWeapon))
        print('Current switch back: ' .. tostring(mapData.fireAndSwitchBackToPrev))

        mapData.action = EntryInputActionEnum.EIASelectWeapon1 + (i - 1)
        mapData.toWeapon = WeaponSwitchingEnum.wsSlot0 + (i - 1)
        mapData.fireAndSwitchBackToPrev = false

        mapData = data.directSwitchMap[i]
        
        print('New action: ' .. tostring(mapData.action))
        print('New weapon: ' .. tostring(mapData.toWeapon))
        print('New switch back: ' .. tostring(mapData.fireAndSwitchBackToPrev))
    end

    -- Set the slot of the grenade.
    data.directSwitchMap[8].toWeapon = WeaponSwitchingEnum.wsSlot5

    -- Set the slot of the knife.    
    data.directSwitchMap[9].toWeapon = WeaponSwitchingEnum.wsSlot4

    -- TODO: Revert these changes when the mod is unloaded.
end

Events:Subscribe('Partition:Loaded', function(partition)
    for _, instance in pairs(partition.instances) do
        if instance.instanceGuid == Guid('FE76DD4D-CA25-2382-1ACB-40117A0AC957') then
            local data = SoldierWeaponSwitchingData(instance)

            print('Found SWSD!')
        
            PatchSWSD(data)
        end
    end
end)

Events:Subscribe('Extension:Loaded', function()
    local instance = ResourceManager:SearchForInstanceByGUID(Guid('FE76DD4D-CA25-2382-1ACB-40117A0AC957'))

    if instance ~= nil then
        local data = SoldierWeaponSwitchingData(instance)

        print('Found SWSD on startup!')
    
        PatchSWSD(data)    
    end
end)
```

This mod will make it so the following buttons map to the following weapon slots, while preventing automatic switching and such. Use this information to set weapons in the appropriate slots when spawning a soldier:

- `1` -> Slot 0
- `2` -> Slot 1
- `3` -> Slot 3
- `4` -> Slot 4
- `5` -> Slot 5
- `6` -> Slot 6

Buttons 7 - 9 are not bound to any key by default, this limits you to 6 items in the inventory (or 8, if you put the knife and grenade in slots that are only accessible via the knife and grenade buttons instead of numbers). I have been unable to make the client switch to slot 2 so far, but I'm looking into it. For now, you should keep slot 2 empty when spawning. You should also set the slots of the knife and grenade in the `PatchSWSD` function, and in general these should be consistent across loadouts (ie. they should be at a specific key for all players, regardless of loadout).

Keep in mind that you will have to revert any changes you make to this instance when your mod unloads, as these changes will persist until a game relaunch. I have not included code for this.

I'm closing this issue for now. I'll open another one about creating an inventory management mod / built-in library.

**Closed as completed by OrfeasZ** 2019-04-21 18:18 UTC
Labels: enhancement, VeniceEXT
