### ISSUE TITLE
Restart client with -ip:port parameters after changing to 60/120Hz

### ISSUE THREAD

**Issue by MAGICCC** [VeniceUnleashed/VeniceUnleashed#165] opened 2015-12-25 23:59 UTC
After selecting a 60/120Hz the client could connect to the server directly after login to the account, so you won't have to reselect the same server.
Also the parameter could be used for a protocol for instant joining servers via a browser-based serverlist

**Comment by OrfeasZ** [comment] 2015-12-26 00:03
Duplicate of #138

**Closed as completed by OrfeasZ** 2015-12-26 00:03 UTC
Labels: duplicate
