### ISSUE TITLE
[Crash] Problem with spawning ObjectBlueprints 

### ISSUE THREAD

**Issue by 3ti65** [VeniceUnleashed/VeniceUnleashed#272] opened 2018-01-18 01:19 UTC
Spawning ObjectBlueprints on client and server crashes the client when the client leaves the server.
No crashdump generated.

**Comment by OrfeasZ** [comment] 2018-01-20 18:38
Please provide a reproduction case

**Comment by 3ti65** [comment] 2018-01-20 22:03
[ObjectSpawnTest.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/1649312/ObjectSpawnTest.zip)

Steps to reproduce:

1. Start up map:
XP3_Shield ConquestLarge0 2

2. Spawn in and type in chat:
'spawn1'

This should have spawned a building on top of you. If not, something is wrong with the testmod or its execution.

3. Press ESC and click on Leave or whatever its called in English. The one that prompts you back to VU menu. 

-> Instead it should crash the client without error message.

**Comment by OrfeasZ** [comment] 2018-01-21 02:34
This seems to be related to decals in some way. Can you try spawning a standalone decal entity and see if it still crashes on exit?

**Comment by OrfeasZ** [comment] 2018-02-03 15:39
Fixed in build 12441.

**Closed as completed by OrfeasZ** 2018-02-03 15:39 UTC
Labels: bug, VeniceEXT
