### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by TheFRPlayer** [VeniceUnleashed/VeniceUnleashed#858] opened 2022-09-25 15:26 UTC
I'm playing since a week but since 3 day i have some crash when i spawn, im playing RealityMod

Crash ID: 601c4c62-322a-453c-9f3e-902f05cc88f5
Build Number: 19072
Release Branch: prod

**Comment by FlashHit** [comment] 2023-03-12 13:53
Duplicate of #879 
If it’s not already fixed then it will with vext 2.0.

**Closed as not planned by FlashHit** 2023-03-12 13:53 UTC
Labels: duplicate
