### ISSUE TITLE
Bulid 10791 Game Disconnect Issue *Update*

### ISSUE THREAD

**Issue by IbrahimSystem** [VeniceUnleashed/VeniceUnleashed#180] opened 2015-12-29 11:24 UTC
My Spces are 
CPU : Intel Core2Duo E8400
GPU : Nvidia GTX 680 
Ram : 8GB DDR3 1333Mhz 
OS : Windows 10 Pro X64 
Before Build 10791
the game disconnect after 10-15 min's 
but now game disconnect after 1-5 mins of the game running time
it say's Connection Lost To Zeus Backend when i click reconnect log in windows pop's up when i hit login 
VU Has stoped working 
Close Program 
and i think that this happen less on 30hz servers 
the game is more stable on 30hz servers  
sorry for bad eng :/

**Comment by OrfeasZ** [comment] 2015-12-31 11:00
Duplicate of #167

**Closed as completed by OrfeasZ** 2015-12-31 11:00 UTC
Labels: duplicate
