### ISSUE TITLE
Bugs in vehicle and while parachuting

### ISSUE THREAD

**Issue by bigworld12** [VeniceUnleashed/VeniceUnleashed#108] opened 2015-05-10 14:02 UTC
is there a problem with the vehicles atm ?
because i can't move well in Heli , parachute

**Comment by OrfeasZ** [comment] 2015-05-10 20:11
Can you be a bit more precise?
What kind of issues are you experiencing in detail?

**Comment by JASTER1** [comment] 2015-05-11 14:36
It seems that the sensitivity is out of wack.  I can barely turn a tank turret, cannot circle in a parachute.  Turned sensitivity all the way up and it was still slow.

**Comment by Bubucho** [comment] 2015-05-11 15:05
Duplicate of #89 i think

**Comment by kiwidoggie** [comment] 2015-05-11 16:29
Duplicate of #89 Vehicle Sensitivity Issues. Closing.

**Closed as completed by kiwidoggie** 2015-05-11 16:29 UTC
Labels: duplicate
