### ISSUE TITLE
[Bug] RegisterEventCallback stops working after modreload

### ISSUE THREAD

**Issue by FlashHit** [VeniceUnleashed/VeniceUnleashed#636] opened 2021-05-07 17:59 UTC
[TestCrash.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/6443487/TestCrash.zip)

Repro:
1. Join server
2. Execute `modList.ReloadExtensions`
3. Press Esc (you need to be spawned)
 -> Client crash

So the registering itself is not the problem. it's when the callback gets triggered.

Note that if you join its not registered, as I do it in Extension:Loaded. So it gets registered the first time after modreload. So it is not that I need to unregister it on unload as its not registered. And it works as expected if you register the eventcallback without modreload.

**Comment by kiwidoggie** [comment] 2021-05-10 08:46
there's a bug with callbacks that they don't get removed on module unload, and fixing the immediate crash prevents the registration from working properly. Pending more work before this can be fixed

**Comment by kiwidoggie** [comment] 2021-05-15 16:08
The crash has been fixed in `17585` on development, there are still unintended behavior, but this will fix the crash. Leaving the issue open until pt2 of this has been fixed.

**Comment by FlashHit** [comment] 2021-06-08 15:30
Atm the callbacks don't work after mod reload, and I get a silent crash when I leave the server after a mod reload.

**Comment by FlashHit** [comment] 2021-07-10 13:52
It is crashing again like before the patch.

**Comment by OrfeasZ** [comment] 2021-07-14 21:45
I can't repro this on `17649`. Can you try again?

**Comment by FlashHit** [comment] 2021-07-14 22:00
With the latest update it is not crashing anymore, but the callback doesn't get fired.

**Comment by OrfeasZ** [comment] 2021-07-14 22:00
This seems to have been an issue with registering callbacks on extension load. It's been fixed in `17653`.

**Closed as completed by OrfeasZ** 2021-07-14 22:00 UTC
Labels: bug, low priority, VeniceEXT
