### ISSUE TITLE
[Bug] Multiple issues with vEXT sockets

### ISSUE THREAD

**Issue by 3ti65** [VeniceUnleashed/VeniceUnleashed#300] opened 2018-04-10 21:06 UTC
- [x] Reloading the extensions with an open socket crashes the client

- [ ] Calling Connect() on a socket that has dropped the connection (eg: the server has closed the socket) does not reconnect correctly (needless to say the server is still listening and accepting connections)

- [x] Re-instantiating a socket on the top of an existing one will make the client crash (myExistingSockThatLostConnection = NetSocket())

**Note:** 

- Calling Destroy() before point 2 or 3 makes either crash or absolutely nothing (won't help make the socket connect again or won't prevent the crash on point 3)
- At this point i wonder if even a Destroy()ed socket will make the client crash on mod reload, worth investigating?

**Comment by OrfeasZ** [comment] 2018-04-22 12:14
These have been fixed in build 12874.

The second "issue" is by design. You can't reconnect a closed socket, you have to create a new one.

**Closed as completed by OrfeasZ** 2018-04-22 12:14 UTC
Labels: bug, high priority, VeniceEXT
